# Generated by Django 5.0.2 on 2024-03-02 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=256, verbose_name='сфера деятельности')),
            ],
            options={
                'verbose_name': 'сфера деятельности',
                'verbose_name_plural': 'сферы деятельности',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256, verbose_name='полное имя')),
                ('born_date', models.DateField(verbose_name='дата рождения')),
                ('image', models.ImageField(upload_to='advertisements/', verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'историческая персона',
                'verbose_name_plural': 'исторические персоны',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='заголовок')),
                ('description', models.TextField(verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(verbose_name='опубликована')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='app_advertisements.articlescope', verbose_name='сфера деятельности')),
                ('persons', models.ManyToManyField(related_name='articles', to='app_advertisements.historicalperson', verbose_name='исторические персоны')),
            ],
            options={
                'verbose_name': 'историческая статья',
                'verbose_name_plural': 'исторические статьи',
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='advertisements/', verbose_name='изображение')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_advertisements.article')),
            ],
        ),
    ]
